import "./globals.css";
import localFont from "next/font/local";
import StyledComponentsRegistry from "@/src/lib/registry";
import { SearchProvider } from "../context/searchContext";
import PageWrapper from "../components/wrapper/page-wrapper";
import Image from "next/image";
import Logo from '@/public/logo-web.png'

const myFont = localFont({
  src: [
    {
      path: "../../src/fonts/PTSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    { path: "../../src/fonts/PTSans-Bold.ttf", weight: "700", style: "bold" },
  ],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        {/*<header className="w-full flex justify-center">
          <Image src={Logo} width={200} height={200} />
        </header>*/}
        <SearchProvider>
          <StyledComponentsRegistry>
           {children}
          </StyledComponentsRegistry>
        </SearchProvider>
      </body>
    </html>
  );
}
